project:
  type: website
  output-dir: docs

website:
  title: "Marijtje::Mode"
  navbar:
    logo: assets/large-dress.png
    left:
      - href: index.qmd
        text: Startseite
      - href: beispiele.qmd
        text: Beispiele
      - href: service.qmd
        text: Service
  page-footer:
    center: 
      - text: "Impressum"
        href: about.qmd
      
format:
  html:
    theme: lux
    css: styles.css
    toc: true



